menu: 
  首页: /
  归档: /archives
  下载: /site
  关于: /about

widgets:
- recent_posts
- category
- tag
#- tagcloud
#- blogroll
excerpt_link: 阅读全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true
#摘要链接文字
excerpt_link: 阅读更多
#按年存档
archive_yearly: true 


# Hexo Beautify
beautify:
  types:
    - html
    - css
    - js
  html:
    'indent_inner_html': false
    'indent_size': 2
    'indent_with_tabs': false
    # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md)
  css:
    'indent_size': 2
    'newline_between_rules': true
    'indent_with_tabs': false
    # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md)
  js:
    'indent_size': 2
    'indent_with_tabs': false
    # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md)
    # 
    # 
    # 
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/
# markdown: 'zero'


# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
# markdown:
#   render:
#     html: true
#     xhtmlOut: false
#     breaks: true
#     linkify: true
#     typographer: true
#     quotes: '“”‘’'
#   plugins:
#     - markdown-it-abbr
#     - markdown-it-footnote
#     - markdown-it-ins
#     - markdown-it-sub
#     - markdown-it-sup
#   anchors:
#     level: 2
#     collisionSuffix: 'v'
#     permalink: true
#     permalinkClass: header-anchor
#     permalinkSymbol: ¶